project_id = "slsdltptkzrfzzcoqxjw"

[functions.chat-with-ainya]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[api]
port = 8000

[db]
port = 5433

[studio]
port = 8001
